language: elixir
elixir:
- 1.4
before_install:
- nvm install 8
cache:
  directories:
  - _build
  - deps
script:
- npm install
- npm install ./deps/phoenix
- npm install ./deps/phoenix_html
- mix deps.get --only prod
- MIX_ENV=prod mix compile
- brunch build --production
- mix phoenix.digest
deploy:
  matrix:
  - provider: heroku
    app: pirates-deploy
    buildpack: https://github.com/HashNuke/heroku-buildpack-elixir.git
    api_key: $HEROKU_API_KEY
    skip_cleanup: true
    on:
      branch: master

  - provider: heroku
    app: pirates-branch-c
    api_key: 75a65060-c8a2-4eaa-ae0c-5ee8bd53fdb5 
    skip_cleanup: true
    on:
      branch: c-myrandom-branch
