language: elixir
elixir:
- 1.4
before_install:
- nvm install 8
cache:
  directories:
  - _build
  - deps
script:
- npm install
- npm install ./deps/phoenix
- npm install ./deps/phoenix_html
- mix deps.get --only prod
- MIX_ENV=prod mix compile
- brunch build --production
- mix phoenix.digest
deploy:
  matrix:
  - provider: heroku
    app: pirates-deploy
    buildpack: https://github.com/HashNuke/heroku-buildpack-elixir.git
    api_key:
      secure: Pxgzetl+0jTxHQ/qEwcoO9BqC6WU6rOc3DHI4bcE+vXdTs57HMMzIh2+kqNIa5euHvTL1EQAdANHETiUvhDukHrkSNR1zL5sRXfB1iaF8SOFYdyloD8K+BNi6er78F5a/LFc8ytbQP6vjLssJFzQ+1oIt2u7xMUVkqHeMvM6VkV7nmjEUbB+7eNnIb2ZouGhkNb66xzybkLx/kPTa7pf4iAhYMNCdPTEp5UkMQjJpNv5XTMZEzbWtbLMdHApvqIexqJyUHulVU15YEitx1rUtvhyoJazg1yXfF88gokATXUEFgPQ9loYnyd/X9QMvxv2T637TtJ+8LQNzmgk/pNGUR04UF1c3iWb9+RXUyDpr7Ib38fKuvVUWeB/4UHmhdZLMb248CSjIqxA4c/HUW04xm6AMBUZHFve8NDw67hVXNaG5TTdaC02rKDfhA287sMRgHEq+Z65D92WKucyEAqB8RuHoHcfJyLCmwNuvak57JvIFqzCauJwDmzcoX1eDnyrtEajM1tGy8IQBU4mP1TJC4Hu3GBZwp3gSbAEOspyr21CFnWSuipzmqICkMpXhyo2kVAU7gZ1Pr5Yu12eR/UAvDS/ALq3gzvqhUr7ezw1VGvmdVJ9vvZyw/3K8hGq0YD4nY1pEz4xq2CFQdbqNmnTcZy3LsNzU3XcfLUfznaeGv0=
    skip_cleanup: true
    on:
      branch: master
      
  - provider: heroku
    app: pirates-branch-c
    api_key:
      secure: Pxgzetl+0jTxHQ/qEwcoO9BqC6WU6rOc3DHI4bcE+vXdTs57HMMzIh2+kqNIa5euHvTL1EQAdANHETiUvhDukHrkSNR1zL5sRXfB1iaF8SOFYdyloD8K+BNi6er78F5a/LFc8ytbQP6vjLssJFzQ+1oIt2u7xMUVkqHeMvM6VkV7nmjEUbB+7eNnIb2ZouGhkNb66xzybkLx/kPTa7pf4iAhYMNCdPTEp5UkMQjJpNv5XTMZEzbWtbLMdHApvqIexqJyUHulVU15YEitx1rUtvhyoJazg1yXfF88gokATXUEFgPQ9loYnyd/X9QMvxv2T637TtJ+8LQNzmgk/pNGUR04UF1c3iWb9+RXUyDpr7Ib38fKuvVUWeB/4UHmhdZLMb248CSjIqxA4c/HUW04xm6AMBUZHFve8NDw67hVXNaG5TTdaC02rKDfhA287sMRgHEq+Z65D92WKucyEAqB8RuHoHcfJyLCmwNuvak57JvIFqzCauJwDmzcoX1eDnyrtEajM1tGy8IQBU4mP1TJC4Hu3GBZwp3gSbAEOspyr21CFnWSuipzmqICkMpXhyo2kVAU7gZ1Pr5Yu12eR/UAvDS/ALq3gzvqhUr7ezw1VGvmdVJ9vvZyw/3K8hGq0YD4nY1pEz4xq2CFQdbqNmnTcZy3LsNzU3XcfLUfznaeGv0=  
    skip_cleanup: true
    on:
      branch: c-myrandom-branch
  
