language: elixir

elixir:
- 1.4

before_install:
- nvm install 8

cache:
  directories:
  - _build
  - deps
  
script:
- npm install
- npm install ./deps/phoenix
- npm install ./deps/phoenix_html
- mix deps.get --only prod
- MIX_ENV=prod mix compile
- brunch build --production
- mix phoenix.digest

deploy:
  - provider: heroku
    app: pirates-deploy
    buildpack: https://github.com/HashNuke/heroku-buildpack-elixir.git
    api_key:
      secure: owL4E5CHX8i0VUHahV4kscbbDB4RW9rEv7jL2YZVQginEu/X0urDIGrX6VWJvfJEJYGlJ4t/GFnkblTHL4kZNOn1QlIAriM3mBHQbqtcjI3rV106KrOtub8X9pToFTiAs4DaBOo95QwanmwVhCRjPnCDQYo2SeEXFGWhUj/liYu6TP08RYX8WSI9rlJ8xVD0r7ii4MrZE6Da81hRQJ1VqmG9Tk5yzrs7phVpJdkrJCHI9bWPT6h1JyDkLvz/rdmSCwlBPQzhPXZXSjvtiUnJxU4Z26OnZuY6sRuLB8/zBydVBxJCPm9MxxmJQYPC405OYMhcyNt9GbIz7WRUvX+bggK0A3q5JDfZh5jOjGTqhveoXd9Nho2JbltPWInlmEcpTftanANul/XUaoHpEMY+FMyrwnqThXsjgIPJhvmY29npU4Xw3TLz4Mx67Q6MmFL3cbRWMlu8FTz3gx5fuLKzkK88SdEDm1ghGVR0pCLHruwyIPw77y/z3DbYdHP0HlEkWDYAOWgmdTuZv5rSRzNo0SNfzXSkZzHmgYTUmaPV8YxD/Ln+9/4RsHEfkaGIFHLC7xG1bLbzUmdu5mELBsz0bRYLtkDcSYkpjfQXqfeETG+kzFyNxn7AzQRhN2ut1z/PKS3+btnfPE0e3ePeGqhMTRqqT1/OXSh9bbh9zF3AI0I=
    skip_cleanup: true
    on:
      branch: master

  - provider: heroku
    app: pirates-branch-c
    api_key:
      secure: owL4E5CHX8i0VUHahV4kscbbDB4RW9rEv7jL2YZVQginEu/X0urDIGrX6VWJvfJEJYGlJ4t/GFnkblTHL4kZNOn1QlIAriM3mBHQbqtcjI3rV106KrOtub8X9pToFTiAs4DaBOo95QwanmwVhCRjPnCDQYo2SeEXFGWhUj/liYu6TP08RYX8WSI9rlJ8xVD0r7ii4MrZE6Da81hRQJ1VqmG9Tk5yzrs7phVpJdkrJCHI9bWPT6h1JyDkLvz/rdmSCwlBPQzhPXZXSjvtiUnJxU4Z26OnZuY6sRuLB8/zBydVBxJCPm9MxxmJQYPC405OYMhcyNt9GbIz7WRUvX+bggK0A3q5JDfZh5jOjGTqhveoXd9Nho2JbltPWInlmEcpTftanANul/XUaoHpEMY+FMyrwnqThXsjgIPJhvmY29npU4Xw3TLz4Mx67Q6MmFL3cbRWMlu8FTz3gx5fuLKzkK88SdEDm1ghGVR0pCLHruwyIPw77y/z3DbYdHP0HlEkWDYAOWgmdTuZv5rSRzNo0SNfzXSkZzHmgYTUmaPV8YxD/Ln+9/4RsHEfkaGIFHLC7xG1bLbzUmdu5mELBsz0bRYLtkDcSYkpjfQXqfeETG+kzFyNxn7AzQRhN2ut1z/PKS3+btnfPE0e3ePeGqhMTRqqT1/OXSh9bbh9zF3AI0I=
    skip_cleanup: true
    on:
      branch: c-myrandom-branch
