language: elixir
elixir:
- 1.4
before_install:
- nvm install 8
cache:
  directories:
  - _build
  - deps
script:
- npm install
- npm install ./deps/phoenix
- npm install ./deps/phoenix_html
- mix deps.get --only prod
- MIX_ENV=prod mix compile
- brunch build --production
- mix phoenix.digest
deploy:
  matrix:
  - provider: heroku
    app: pirates-deploy
    buildpack: https://github.com/HashNuke/heroku-buildpack-elixir.git
    api_key:
      secure: Ac6Y341ieSgTxdcGoD3rADx6P2qYhx94QJ+Zkn3xS+KkldZPk43C+U/EOPNIhrsPyCqXf20s0ytR35L1GM/vPod59IV+a3H2QeUN0AtzOwfaDi/9E6pGPXeORIGPaO1pDHqzIEJmm+5Li9ZExVl4sWHMr3dOD0yrC5UCNju0i0ypxInFDaC2+W/zRfqnvNWk08ZRBoHx20D9ouAk+in/vfYEtel/vlbgCnLUB3BQFGrVxJGpp3FL4ZSs7xFpzFpMbWeYBF03nzeXrzrOZDKwm0WFMhGpQZUHngH/efyuT11GSQuT/lx78JlyZ9dxYtt5LNewtttB8+2yH4Ad/SGLtsVt/HE99lmyEuPD0vfPxEw0eduCOttUNsWy0+mD/DWTa1+Y0nZqlkL9/uFDq2+cgPuwLMCSL0C6cn6mENkjtEZ/bZR4eajtlZnZauvbxnXl+QbA/Jm9H3KbCJtzuSs6PjTPqWRtzFdGXah8Ljr/NiUW3rKjEy3grLi0B5UIMWnal27PdyyibhGwOrSoaH+/bgmhNQGh6LeHFLue7X4IHAVQl4wciA4wGeRXDS8+8ovpFTlhhiKz1AOou8KvqSKS/7Dw6mAxpmlPtv81eiDJzzcnHndf4HWsaojkPqNSJHFaP2E63kVDGRPgbTvKrOKphU4uuWWB6DyetZiVAiZ7r8I=
    skip_cleanup: true
    on:
      branch: master

  - provider: heroku
    app: pirates-branch-c
    api_key:
      secure: Ac6Y341ieSgTxdcGoD3rADx6P2qYhx94QJ+Zkn3xS+KkldZPk43C+U/EOPNIhrsPyCqXf20s0ytR35L1GM/vPod59IV+a3H2QeUN0AtzOwfaDi/9E6pGPXeORIGPaO1pDHqzIEJmm+5Li9ZExVl4sWHMr3dOD0yrC5UCNju0i0ypxInFDaC2+W/zRfqnvNWk08ZRBoHx20D9ouAk+in/vfYEtel/vlbgCnLUB3BQFGrVxJGpp3FL4ZSs7xFpzFpMbWeYBF03nzeXrzrOZDKwm0WFMhGpQZUHngH/efyuT11GSQuT/lx78JlyZ9dxYtt5LNewtttB8+2yH4Ad/SGLtsVt/HE99lmyEuPD0vfPxEw0eduCOttUNsWy0+mD/DWTa1+Y0nZqlkL9/uFDq2+cgPuwLMCSL0C6cn6mENkjtEZ/bZR4eajtlZnZauvbxnXl+QbA/Jm9H3KbCJtzuSs6PjTPqWRtzFdGXah8Ljr/NiUW3rKjEy3grLi0B5UIMWnal27PdyyibhGwOrSoaH+/bgmhNQGh6LeHFLue7X4IHAVQl4wciA4wGeRXDS8+8ovpFTlhhiKz1AOou8KvqSKS/7Dw6mAxpmlPtv81eiDJzzcnHndf4HWsaojkPqNSJHFaP2E63kVDGRPgbTvKrOKphU4uuWWB6DyetZiVAiZ7r8I=
    skip_cleanup: true
    on:
      branch: c-myrandom-branch
  
